version: "3.8"

services:
  # Local PostgreSQL for development
  db:
    image: postgres:15-alpine
    container_name: notification_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: notification_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
